TERMUX_PKG_HOMEPAGE=https://github.com/nlohmann/json
TERMUX_PKG_DESCRIPTION="JSON for Modern C++"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE.MIT"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION="3.11.3"
TERMUX_PKG_SRCURL=https://github.com/nlohmann/json/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0d8ef5af7f9794e3263480193c491549b2ba6cc74bb018906202ada498a79406
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=None
-DJSON_MultipleHeaders=ON
-DJSON_BuildTests=off
-Wno-dev
"
