TERMUX_PKG_HOMEPAGE=https://github.com/google/cppdap
TERMUX_PKG_DESCRIPTION="C++ library for the Debug Adapter Protocol"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=1.58.0
TERMUX_PKG_SRCURL=https://github.com/google/cppdap/archive/dap-$TERMUX_PKG_VERSION-a.tar.gz
TERMUX_PKG_SHA256=5d35ca5db78570b6bef698e3365f79bd82a4f78e8393546387f78d7bdb2a2a08
TERMUX_PKG_DEPENDS="gcc-libs-glibc"
TERMUX_PKG_BUILD_DEPENDS="nlohmann-json-glibc"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCPPDAP_USE_EXTERNAL_NLOHMANN_JSON_PACKAGE=ON
-DBUILD_SHARED_LIBS=ON
"
