TERMUX_PKG_HOMEPAGE=https://linux.thai.net/projects/datrie
TERMUX_PKG_DESCRIPTION="Thai language support library"
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=0.1.30
TERMUX_PKG_SRCURL=https://linux.thai.net/pub/thailinux/software/libthai/libthai-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=ddba8b53dfe584c3253766030218a88825488a51a7deef041d096e715af64bdd
TERMUX_PKG_DEPENDS="libdatrie-glibc"
TERMUX_PKG_BUILD_DEPENDS="doxygen-glibc"
TERMUX_PKG_BUILD_IN_SRC=true
