TERMUX_PKG_HOMEPAGE=https://github.com/ptitSeb/box86
TERMUX_PKG_DESCRIPTION="Linux Userspace x86 Emulator with a twist"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=0.3.8
TERMUX_PKG_SRCURL=https://github.com/ptitSeb/box86/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=454e5f7c57f7c7c4530d4f453bf6afd07b00bd93c92fe16a4305bacae0b6a93d
TERMUX_PKG_DEPENDS="gcc-libs-glibc"
TERMUX_PKG_BLACKLISTED_ARCHES="aarch64, x86_64, i686"
TERMUX_CMAKE_BUILD="Unix Makefiles"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DARM_DYNAREC=ON
-DCMAKE_BUILD_TYPE=RelWithDebInfo
-DCMAKE_HOST_SYSTEM_PROCESSOR=${TERMUX_ARCH}
"
