TERMUX_PKG_HOMEPAGE=https://www.nongnu.org/libunwind/
TERMUX_PKG_DESCRIPTION="Determine and manipulate the call-chain of a program"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=1.8.2
TERMUX_PKG_SRCURL=https://github.com/libunwind/libunwind/releases/download/v$TERMUX_PKG_VERSION/libunwind-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=7f262f1a1224f437ede0f96a6932b582c8f5421ff207c04e3d9504dfa04c8b82
TERMUX_PKG_DEPENDS="zlib-glibc, liblzma-glibc"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-tests"
