TERMUX_PKG_HOMEPAGE=https://github.com/rockdaboot/libpsl
TERMUX_PKG_DESCRIPTION="Public Suffix List library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION="0.23.0"
TERMUX_PKG_SRCURL=https://github.com/rockdaboot/libpsl/releases/download/${TERMUX_PKG_VERSION}/libpsl-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=f39b9631b3d369a21259ea4654f8875c0ec6995ce9551c0eb5d423e4c011f911
TERMUX_PKG_DEPENDS="libidn2-glibc, libunistring-glibc"
TERMUX_PKG_BUILD_DEPENDS="publicsuffix-list-glibc"
