TERMUX_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-Headers
TERMUX_PKG_DESCRIPTION="SPIR-V Headers"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION="1.3.280.0"
TERMUX_PKG_SRCURL=https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-${TERMUX_PKG_VERSION}/spirv-headers-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a00906b6bddaac1e37192eff2704582f82ce2d971f1aacee4d51d9db33b0f772
TERMUX_PKG_PLATFORM_INDEPENDENT=true
