TERMUX_PKG_HOMEPAGE=https://www.pango.org/
TERMUX_PKG_DESCRIPTION="Library for laying out and rendering text"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=1.52.2
TERMUX_PKG_SRCURL=https://gitlab.gnome.org/GNOME/pango/-/archive/${TERMUX_PKG_VERSION}/pango-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a104a4c4353b59aa3de7018f53f61ac0ab5a3504734adc288971979a1151100c
TERMUX_PKG_DEPENDS="libcairo-glibc, fribidi-glibc, harfbuzz-glibc, libthai-glibc, libxft-glibc"
TERMUX_PKG_BUILD_DEPENDS="gobject-introspection-glibc"
