TERMUX_PKG_HOMEPAGE=https://github.com/silnrsi/graphite
TERMUX_PKG_DESCRIPTION="Font system for multiple languages"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=1.3.15
TERMUX_PKG_SRCURL=https://github.com/silnrsi/graphite/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ad47ac120d0fbd80dbc93669afd1074fbbf68af8d1bedf936cf1a433c170f565
TERMUX_PKG_DEPENDS="gcc-libs-glibc"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=None
-DCMAKE_SKIP_INSTALL_RPATH=ON
-DGRAPHITE2_COMPARE_RENDERER=OFF
-DGRAPHITE2_VM_TYPE=direct
"
