TERMUX_PKG_HOMEPAGE=https://aomedia.org/
TERMUX_PKG_DESCRIPTION="AV1 Video Codec Library"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE, PATENTS"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=3.12.0
TERMUX_PKG_SRCURL=https://storage.googleapis.com/aom-releases/libaom-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=d89daa160a0ea1409c4193be5b17c9591024c4f5a0e545dcb9d197535c66836e
TERMUX_PKG_DEPENDS="glibc"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=1
-DENABLE_TESTS=0
"

termux_step_pre_configure() {
	if [ "$TERMUX_ARCH" = "arm" ]; then
		TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DAOM_TARGET_CPU=generic"
	fi
	CFLAGS="${CFLAGS/-O2/-O3}"
	CXXFLAGS="${CXXFLAGS/-O2/-O3}"
}
