TERMUX_PKG_HOMEPAGE=https://aomedia.org/
TERMUX_PKG_DESCRIPTION="AV1 Video Codec Library"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE, PATENTS"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=3.8.0
TERMUX_PKG_SRCURL=https://storage.googleapis.com/aom-releases/libaom-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=a768d3e54c7f00cd38b01208d1ae52d671be410cfc387ff7881ea71c855f3600
TERMUX_PKG_DEPENDS="glibc"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=None
-DBUILD_SHARED_LIBS=1
-DENABLE_TESTS=0
"

termux_step_pre_configure() {
	CFLAGS="${CFLAGS/-O2/-O3}"
	CXXFLAGS="${CXXFLAGS/-O2/-O3}"
}
